-- Migration 201: Engineering/Product Development module, first release
-- (decision D14). Design doc: PRODUCT_ENGINEERING_MODULE_DESIGN.md
-- (Queue B8) -- revalidated against the CURRENT schema before writing
-- this (2026-09-23), same discipline as migration 200 (Support). Two
-- concrete facts checked directly rather than assumed from the design
-- doc's own illustrative schema:
--   1. `product_catalog` (migration 013, workspace-scoped by migration
--      176) already has its own real `workspace_id` column and its own
--      `guard_workspace_id_mutation()` trigger -- `product_requests`
--      follows the exact same root-table shape (own workspace_id,
--      directly listable), matching `product_catalog`/`projects`, not a
--      derived-workspace child table.
--   2. `product_catalog`'s own write policy (migration 176) is
--      `is_app_admin() or has_role('manager')` ONLY -- `engineering` has
--      no direct catalog write access today. The design doc's own §6
--      flags "who may trigger the Catalog write" as genuinely
--      undecided -- resolved here as: `engineering` (or an app admin)
--      triggers release through a dedicated, audited
--      `release_product_request()` RPC that performs the catalog write
--      as SECURITY DEFINER, rather than broadening `product_catalog`'s
--      own raw-table RLS to a role that has no reason to write to the
--      catalog directly outside this one controlled path. Matches this
--      schema's own repeated preference for a controlled RPC over
--      widened raw RLS (e.g. `catalog_price_change_requests`).
--   3. `catalog_number` is a plain, manually-entered, unique-per-workspace
--      text field today (confirmed via `createCatalogItem`'s own client
--      code, `src/persistence.ts`) -- not auto-generated by a ref
--      counter. `release_product_request()`'s "new product" mode
--      therefore takes an explicit `p_catalog_number` parameter rather
--      than inventing a new auto-numbering scheme that would diverge
--      from how every other catalog item is created.
--
-- Two of the design doc's own §6 open permission questions are resolved
-- explicitly here, not left ambiguous:
--   - Submission is open to ANY active workspace member (the design
--     doc's own "recommended yes... submission is lower-stakes than
--     review" reasoning, and matches this schema's existing precedent
--     for low-risk actions like Tasks being open to any member).
--   - Review/status-transition/release actions are gated to
--     `engineering`/`product_development`/an app admin, matching the
--     read/write split their existing Inventory permissions already
--     imply (design doc §6, "recommended, not decided" -- decided here).
--
-- Explicitly OUT of scope for this release (unchanged from the design
-- doc's own §7): the Support-case handoff link (Support now exists,
-- migration 200, but this module deliberately does not add that FK
-- yet -- a real, small, additive follow-up, not attempted in this
-- already-large batch); a formal structured requirements schema (stays
-- free text, matching `bundle_components`' own still-open precedent).

begin;

-- ============================================================
-- Section 1 -- product_requests. Root table, own workspace_id, stamped
-- server-side via resolve_caller_workspace_id() in the same trigger that
-- generates request_number ("PR-<year>-####", workspace-scoped ref
-- counter -- identical shape to migration 200's support_case_ref_counters).
-- The optional source_project_id, when supplied, is cross-checked against
-- the caller's own resolved workspace, same containment discipline as
-- migration 200's project_id check.
-- ============================================================

create table if not exists public.product_requests (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id),
  request_number text not null,
  title text not null check (char_length(btrim(title)) > 0),
  source_project_id uuid references public.projects(id),
  source_client_name text,
  requested_by_email text not null,
  status text not null default 'submitted' check (status in (
    'submitted', 'requirements_review', 'technical_review', 'prototyping',
    'release_ready', 'released', 'declined', 'on_hold'
  )),
  requirements text,
  released_catalog_item_id uuid references public.product_catalog(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workspace_id, request_number)
);

create index if not exists idx_product_requests_workspace_id on public.product_requests(workspace_id);
create index if not exists idx_product_requests_status on public.product_requests(workspace_id, status);
create index if not exists idx_product_requests_source_project on public.product_requests(source_project_id);

create table if not exists public.product_request_ref_counters (
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  year integer not null,
  next_seq integer not null default 1,
  primary key (workspace_id, year)
);

alter table public.product_request_ref_counters enable row level security;

create policy "workspace members read product_request_ref_counters"
  on public.product_request_ref_counters for select to authenticated
  using (public.is_workspace_member(workspace_id));

create or replace function public.assign_product_request_ref()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_workspace_id uuid;
  v_project_workspace_id uuid;
  ref_year integer := extract(year from pg_catalog.now())::integer;
  seq integer;
begin
  v_workspace_id := public.resolve_caller_workspace_id();

  if new.source_project_id is not null then
    v_project_workspace_id := (select workspace_id from public.projects where id = new.source_project_id);
    if v_project_workspace_id is null then
      raise exception 'The selected source project was not found.';
    end if;
    if v_project_workspace_id <> v_workspace_id then
      raise exception 'That project does not belong to your workspace.';
    end if;
  end if;

  new.workspace_id := v_workspace_id;

  if new.request_number is null then
    insert into public.product_request_ref_counters as prrc (workspace_id, year, next_seq)
    values (v_workspace_id, ref_year, 2)
    on conflict (workspace_id, year) do update set next_seq = prrc.next_seq + 1
    returning next_seq - 1 into seq;

    new.request_number := 'PR-' || ref_year || '-' || pg_catalog.lpad(seq::text, 4, '0');
  end if;

  new.updated_at := pg_catalog.now();
  return new;
end;
$$;

revoke all on function public.assign_product_request_ref() from public;

drop trigger if exists product_requests_assign_ref on public.product_requests;
create trigger product_requests_assign_ref
  before insert on public.product_requests
  for each row execute function public.assign_product_request_ref();

create or replace function public.touch_product_request_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := pg_catalog.now();
  return new;
end;
$$;

drop trigger if exists product_requests_touch_updated_at on public.product_requests;
create trigger product_requests_touch_updated_at
  before update on public.product_requests
  for each row execute function public.touch_product_request_updated_at();

create or replace function public.guard_product_request_workspace_id_mutation()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.workspace_id <> old.workspace_id then
    raise exception 'workspace_id cannot be changed on an existing product request';
  end if;
  return new;
end;
$$;

revoke all on function public.guard_product_request_workspace_id_mutation() from public;

drop trigger if exists product_requests_guard_workspace_id on public.product_requests;
create trigger product_requests_guard_workspace_id
  before update on public.product_requests
  for each row execute function public.guard_product_request_workspace_id_mutation();

alter table public.product_requests enable row level security;

create policy "workspace members read product_requests"
  on public.product_requests for select to authenticated
  using (public.is_workspace_member(workspace_id));

-- Submission is open to any active workspace member -- design doc §6's
-- own "recommended yes, submission is lower-stakes than review."
create policy "workspace members insert product_requests"
  on public.product_requests for insert to authenticated
  with check (public.is_active_workspace_member(workspace_id));

-- No update policy at all -- every status transition, review, and the
-- catalog release itself goes through the SECURITY DEFINER functions
-- below, never a raw client PATCH. Stricter than migration 200's
-- support_cases (which does allow a generic authenticated UPDATE policy)
-- because this table's own status field drives a real approval/release
-- workflow with role-gated transitions RLS alone cannot express cleanly.

-- No delete policy -- never hard-deleted, only moved to 'declined'.

-- ============================================================
-- Section 2 -- product_request_reviews. Append-only, same
-- SELECT-only-via-RPC-INSERT shape as migration 200's
-- support_case_activity. kind='status_change' rows are the plain audit
-- trail for every transition (including ones with no review outcome,
-- e.g. moving into on_hold); kind in
-- ('technical_review','prototype_test') rows carry a real pass/fail/
-- needs_revision outcome and drive the automatic status transitions
-- inside log_product_request_review() below; kind='release_readiness'
-- is written once, automatically, by release_product_request() itself.
-- ============================================================

create or replace function public.product_request_owner_workspace_id(p_product_request_id uuid)
returns uuid
language sql
security definer
stable
set search_path = ''
as $$
  select workspace_id from public.product_requests where id = p_product_request_id;
$$;

revoke all on function public.product_request_owner_workspace_id(uuid) from public;
revoke execute on function public.product_request_owner_workspace_id(uuid) from anon;
grant execute on function public.product_request_owner_workspace_id(uuid) to authenticated;

create table if not exists public.product_request_reviews (
  id uuid primary key default gen_random_uuid(),
  product_request_id uuid not null references public.product_requests(id) on delete cascade,
  kind text not null check (kind in ('technical_review', 'prototype_test', 'release_readiness', 'status_change')),
  outcome text check (outcome in ('pass', 'fail', 'needs_revision')),
  notes text,
  previous_status text,
  new_status text,
  reviewed_by_email text not null,
  -- clock_timestamp(), not now() -- migration 198's own already-found bug
  -- (an audit log's timestamp must reflect the real moment each row is
  -- written, not freeze at the surrounding transaction's start time; this
  -- only differs from now() when two rows are written in the same
  -- transaction, exactly what this migration's own canonical test does
  -- and what real multi-step review flows can also do in a single RPC
  -- call, e.g. log_product_request_review's own review-row-then-
  -- status-change-row pair).
  reviewed_at timestamptz not null default clock_timestamp()
);

create index if not exists idx_product_request_reviews_request on public.product_request_reviews(product_request_id, reviewed_at desc);

alter table public.product_request_reviews enable row level security;

create policy "workspace members read product_request_reviews"
  on public.product_request_reviews for select to authenticated
  using (public.is_workspace_member(public.product_request_owner_workspace_id(product_request_id)));

-- No insert policy for `authenticated` at all -- every row is written by
-- one of the SECURITY DEFINER functions below, so reviewed_by_email is
-- always the real caller's own address.

-- ============================================================
-- Section 3 -- create_product_request(). Open to any active workspace
-- member (design doc §6).
-- ============================================================

create or replace function public.create_product_request(
  p_title text,
  p_requirements text default null,
  p_source_project_id uuid default null,
  p_source_client_name text default null
)
returns public.product_requests
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_email text;
  v_request public.product_requests;
begin
  if v_actor_id is null then
    raise exception 'Must be signed in to submit a product request';
  end if;
  if p_title is null or char_length(btrim(p_title)) = 0 then
    raise exception 'A title is required';
  end if;

  select email into v_actor_email from auth.users where id = v_actor_id;
  if v_actor_email is null then
    raise exception 'Could not resolve the signed-in user''s email';
  end if;

  insert into public.product_requests (title, requirements, source_project_id, source_client_name, requested_by_email)
  values (btrim(p_title), nullif(btrim(coalesce(p_requirements, '')), ''), p_source_project_id, nullif(btrim(coalesce(p_source_client_name, '')), ''), v_actor_email)
  returning * into v_request;

  insert into public.product_request_reviews (product_request_id, kind, notes, reviewed_by_email, new_status)
  values (v_request.id, 'status_change', 'Request submitted.', v_actor_email, 'submitted');

  return v_request;
end;
$$;

revoke all on function public.create_product_request(text, text, uuid, text) from public;
revoke execute on function public.create_product_request(text, text, uuid, text) from anon;
grant execute on function public.create_product_request(text, text, uuid, text) to authenticated;

-- ============================================================
-- Section 4 -- role gate shared by every review/status/release
-- function below. Matches product_catalog's own established
-- is_app_admin()-or-has_role() shape (migration 176) -- engineering and
-- product_development are the two roles this module actually belongs to
-- (design doc §1); an app admin can always act too, same escape hatch
-- every other role-gated table in this schema keeps.
-- ============================================================

create or replace function public.can_review_product_requests()
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select public.is_app_admin(auth.uid()) or public.has_role('engineering') or public.has_role('product_development');
$$;

revoke all on function public.can_review_product_requests() from public;
revoke execute on function public.can_review_product_requests() from anon;
grant execute on function public.can_review_product_requests() to authenticated;

-- ============================================================
-- Section 5 -- log_product_request_review(). technical_review/
-- prototype_test only -- release_readiness is written exclusively by
-- release_product_request() below, matching migration 200's own
-- discipline of keeping the "big" transition in its own dedicated
-- function. A review's outcome automatically advances (or does not
-- advance) the request's own status, logged as a SEPARATE, immediately
-- following status_change row in the SAME transaction -- both rows
-- exist, so "why did the status change" is always answerable from the
-- review row sitting right next to it, but "what's the current status"
-- never requires re-deriving it from review history.
-- ============================================================

create or replace function public.log_product_request_review(
  p_product_request_id uuid,
  p_kind text,
  p_outcome text,
  p_notes text default null
)
returns public.product_request_reviews
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_email text;
  v_request public.product_requests;
  v_review public.product_request_reviews;
  v_new_status text;
begin
  if v_actor_id is null then
    raise exception 'Must be signed in to log a review';
  end if;
  if p_kind not in ('technical_review', 'prototype_test') then
    raise exception 'log_product_request_review only accepts technical_review or prototype_test -- use release_product_request() for release_readiness';
  end if;
  if p_outcome not in ('pass', 'fail', 'needs_revision') then
    raise exception 'outcome must be pass, fail, or needs_revision';
  end if;

  select email into v_actor_email from auth.users where id = v_actor_id;
  if v_actor_email is null then
    raise exception 'Could not resolve the signed-in user''s email';
  end if;

  select * into v_request from public.product_requests where id = p_product_request_id for update;
  if v_request.id is null then
    raise exception 'Product request not found';
  end if;
  if not public.is_active_workspace_member(v_request.workspace_id) then
    raise exception 'Not an active member of this request''s workspace';
  end if;
  if not public.can_review_product_requests() then
    raise exception 'Only engineering, product development, or an admin may log a review';
  end if;
  if v_request.status in ('released', 'declined') then
    raise exception 'Cannot log a review against a % request', v_request.status;
  end if;

  if p_kind = 'technical_review' then
    v_new_status := case p_outcome
      when 'pass' then 'prototyping'
      when 'fail' then 'declined'
      when 'needs_revision' then 'requirements_review'
    end;
  else
    -- prototype_test: pass moves it forward to release_ready; fail/
    -- needs_revision stay in prototyping so a retry can be logged
    -- without forcing a manual status move first.
    v_new_status := case p_outcome
      when 'pass' then 'release_ready'
      else 'prototyping'
    end;
  end if;

  insert into public.product_request_reviews (product_request_id, kind, outcome, notes, reviewed_by_email)
  values (p_product_request_id, p_kind, p_outcome, nullif(btrim(coalesce(p_notes, '')), ''), v_actor_email)
  returning * into v_review;

  if v_new_status is distinct from v_request.status then
    insert into public.product_request_reviews (product_request_id, kind, notes, reviewed_by_email, previous_status, new_status)
    values (p_product_request_id, 'status_change', 'Automatic, from ' || p_kind || ' outcome: ' || p_outcome || '.', v_actor_email, v_request.status, v_new_status);

    update public.product_requests set status = v_new_status where id = p_product_request_id;
  end if;

  return v_review;
end;
$$;

revoke all on function public.log_product_request_review(uuid, text, text, text) from public;
revoke execute on function public.log_product_request_review(uuid, text, text, text) from anon;
grant execute on function public.log_product_request_review(uuid, text, text, text) to authenticated;

-- ============================================================
-- Section 6 -- change_product_request_status(). Manual moves not driven
-- by a review outcome -- e.g. product_development moving a request into
-- requirements_review, putting it on_hold, or declining it outright at
-- any pre-release point. Deliberately rejects 'released' (only reachable
-- via release_product_request()) and rejects moving FROM 'released'/
-- 'declined' at all (both are terminal in this release -- no reopen
-- concept for product requests, unlike Support's cases).
-- ============================================================

create or replace function public.change_product_request_status(
  p_product_request_id uuid,
  p_new_status text,
  p_note text default null
)
returns public.product_requests
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_email text;
  v_request public.product_requests;
  v_previous_status text;
begin
  if v_actor_id is null then
    raise exception 'Must be signed in to change a product request''s status';
  end if;
  if p_new_status not in ('submitted', 'requirements_review', 'technical_review', 'prototyping', 'on_hold', 'declined') then
    raise exception 'Invalid target status: % (use release_product_request() to reach released)', p_new_status;
  end if;

  select email into v_actor_email from auth.users where id = v_actor_id;
  if v_actor_email is null then
    raise exception 'Could not resolve the signed-in user''s email';
  end if;

  select * into v_request from public.product_requests where id = p_product_request_id for update;
  if v_request.id is null then
    raise exception 'Product request not found';
  end if;
  if not public.is_active_workspace_member(v_request.workspace_id) then
    raise exception 'Not an active member of this request''s workspace';
  end if;
  if not public.can_review_product_requests() then
    raise exception 'Only engineering, product development, or an admin may change a request''s status';
  end if;
  if v_request.status in ('released', 'declined') then
    raise exception 'Cannot change the status of a % request', v_request.status;
  end if;
  if p_new_status = v_request.status then
    raise exception 'Product request is already %', p_new_status;
  end if;

  v_previous_status := v_request.status;

  update public.product_requests set status = p_new_status where id = p_product_request_id;

  insert into public.product_request_reviews (product_request_id, kind, notes, reviewed_by_email, previous_status, new_status)
  values (p_product_request_id, 'status_change', nullif(btrim(coalesce(p_note, '')), ''), v_actor_email, v_previous_status, p_new_status);

  select * into v_request from public.product_requests where id = p_product_request_id;
  return v_request;
end;
$$;

revoke all on function public.change_product_request_status(uuid, text, text) from public;
revoke execute on function public.change_product_request_status(uuid, text, text) from anon;
grant execute on function public.change_product_request_status(uuid, text, text) to authenticated;

-- ============================================================
-- Section 7 -- release_product_request(). Only from 'release_ready'.
-- mode='new' inserts a real product_catalog row (SECURITY DEFINER,
-- bypassing product_catalog's own manager/admin-only write RLS by
-- design -- see this file's own header); mode='update' updates an
-- EXISTING catalog item, cross-checked to belong to the SAME workspace.
-- Either way this is the ONLY place released_catalog_item_id is ever
-- set, and the only place a request reaches status='released'.
-- ============================================================

create or replace function public.release_product_request(
  p_product_request_id uuid,
  p_mode text,
  p_existing_catalog_item_id uuid default null,
  p_catalog_number text default null,
  p_product_name text default null,
  p_sales_description text default null,
  p_technical_description text default null,
  p_category text default null,
  p_default_sell_price numeric default 0,
  p_notes text default null
)
returns public.product_requests
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_email text;
  v_request public.product_requests;
  v_catalog_item_id uuid;
  v_existing_workspace_id uuid;
begin
  if v_actor_id is null then
    raise exception 'Must be signed in to release a product request';
  end if;
  if p_mode not in ('new', 'update') then
    raise exception 'mode must be new or update';
  end if;

  select email into v_actor_email from auth.users where id = v_actor_id;
  if v_actor_email is null then
    raise exception 'Could not resolve the signed-in user''s email';
  end if;

  select * into v_request from public.product_requests where id = p_product_request_id for update;
  if v_request.id is null then
    raise exception 'Product request not found';
  end if;
  if not public.is_active_workspace_member(v_request.workspace_id) then
    raise exception 'Not an active member of this request''s workspace';
  end if;
  if not (public.is_app_admin(auth.uid()) or public.has_role('engineering')) then
    raise exception 'Only engineering or an admin may release a product request';
  end if;
  if v_request.status <> 'release_ready' then
    raise exception 'Only a release_ready request can be released (current status: %)', v_request.status;
  end if;

  if p_mode = 'new' then
    if p_catalog_number is null or char_length(btrim(p_catalog_number)) = 0 then
      raise exception 'catalog_number is required to release a new catalog item';
    end if;
    insert into public.product_catalog (workspace_id, catalog_number, product_name, sales_description, technical_description, category, default_sell_price)
    values (
      v_request.workspace_id,
      btrim(p_catalog_number),
      coalesce(nullif(btrim(coalesce(p_product_name, '')), ''), v_request.title),
      nullif(btrim(coalesce(p_sales_description, '')), ''),
      nullif(btrim(coalesce(p_technical_description, '')), ''),
      nullif(btrim(coalesce(p_category, '')), ''),
      coalesce(p_default_sell_price, 0)
    )
    returning id into v_catalog_item_id;
  else
    if p_existing_catalog_item_id is null then
      raise exception 'existing_catalog_item_id is required for mode=update';
    end if;
    select workspace_id into v_existing_workspace_id from public.product_catalog where id = p_existing_catalog_item_id;
    if v_existing_workspace_id is null then
      raise exception 'Catalog item not found';
    end if;
    if v_existing_workspace_id <> v_request.workspace_id then
      raise exception 'That catalog item does not belong to this request''s workspace';
    end if;
    update public.product_catalog
    set product_name = coalesce(nullif(btrim(coalesce(p_product_name, '')), ''), product_name),
        sales_description = coalesce(nullif(btrim(coalesce(p_sales_description, '')), ''), sales_description),
        technical_description = coalesce(nullif(btrim(coalesce(p_technical_description, '')), ''), technical_description),
        category = coalesce(nullif(btrim(coalesce(p_category, '')), ''), category),
        default_sell_price = coalesce(p_default_sell_price, default_sell_price),
        updated_at = now()
    where id = p_existing_catalog_item_id;
    v_catalog_item_id := p_existing_catalog_item_id;
  end if;

  update public.product_requests
  set status = 'released', released_catalog_item_id = v_catalog_item_id
  where id = p_product_request_id
  returning * into v_request;

  insert into public.product_request_reviews (product_request_id, kind, outcome, notes, reviewed_by_email, previous_status, new_status)
  values (p_product_request_id, 'release_readiness', 'pass', nullif(btrim(coalesce(p_notes, '')), ''), v_actor_email, 'release_ready', 'released');

  return v_request;
end;
$$;

revoke all on function public.release_product_request(uuid, text, uuid, text, text, text, text, text, numeric, text) from public;
revoke execute on function public.release_product_request(uuid, text, uuid, text, text, text, text, text, numeric, text) from anon;
grant execute on function public.release_product_request(uuid, text, uuid, text, text, text, text, text, numeric, text) to authenticated;

-- ============================================================
-- Section 8 -- notification_rules: register product_request_reviewed so
-- Admin's existing per-event channel toggle covers it too, matching
-- migration 200's own item 9.
-- ============================================================

alter table public.notification_rules drop constraint if exists notification_rules_event_type_check;
alter table public.notification_rules add constraint notification_rules_event_type_check
  check (event_type in (
    'build_stage_changed', 'catalog_price_change_requested', 'catalog_price_change_reviewed',
    'direct_message_received', 'low_stock_reached', 'mentioned',
    'purchase_request_status_changed', 'quote_proposal_responded', 'submittal_responded',
    'task_assigned', 'task_overdue', 'task_status_changed', 'user_signup_pending',
    'proposal_question_received', 'support_case_assigned', 'product_request_reviewed'
  ));

commit;
